[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=lib/forge-std/src/"
]
